from pathlib import Path
import json
import sys

import matplotlib.pyplot as plt
import pandas as pd
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE, MSO_CONNECTOR
from pptx.dml.color import RGBColor

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'src'))
from features import structural_features  # noqa
from plot_assets import generate_plot_assets  # noqa

DATA = ROOT / 'data' / 'sample_sms.csv'
METRICS = ROOT / 'models' / 'metrics.json'
ASSETS = ROOT / 'docs' / 'assets'
OUT = ROOT / 'docs' / 'CGIS_SMS_Scam_Detector_Winning_Bilingual.pptx'
ASSETS.mkdir(parents=True, exist_ok=True)

# ---------- Analytics charts ----------
# Refresh shared plot assets from the latest training metrics and dataset.
latest_assets = generate_plot_assets()

df = pd.read_csv(DATA)
feat_df = pd.DataFrame([structural_features(t) for t in df['text']])
analytics = pd.concat([df[['label']], feat_df], axis=1)

# Chart 1: label distribution
label_counts = df['label'].value_counts().reindex(['ham','spam','smishing']).fillna(0)
colors = {'ham':'#16a34a','spam':'#f59e0b','smishing':'#dc2626'}
plt.figure(figsize=(7.2, 4.2), dpi=180)
bars = plt.bar(label_counts.index, label_counts.values, color=[colors[x] for x in label_counts.index])
plt.title('Prototype Dataset Label Distribution', fontsize=14, fontweight='bold')
plt.ylabel('Number of SMS')
plt.grid(axis='y', alpha=0.25)
for b in bars:
    plt.text(b.get_x()+b.get_width()/2, b.get_height()+0.15, str(int(b.get_height())), ha='center', fontsize=11, fontweight='bold')
plt.tight_layout()
label_chart = ASSETS / 'label_distribution.png'
plt.savefig(label_chart, transparent=False, facecolor='white')
plt.close()

# Chart 2: suspicious signal prevalence by class
signals = ['has_url','has_phone','has_money','has_otp_pin']
prev = analytics.groupby('label')[signals].mean().reindex(['ham','spam','smishing']).fillna(0) * 100
plt.figure(figsize=(8.0, 4.4), dpi=180)
prev.T.plot(kind='bar', color=[colors.get(c,'#2563eb') for c in prev.index], ax=plt.gca())
plt.title('Risk Signal Prevalence by Class', fontsize=14, fontweight='bold')
plt.ylabel('% of messages')
plt.xticks(rotation=25, ha='right')
plt.ylim(0, 105)
plt.grid(axis='y', alpha=0.25)
plt.legend(title='Class')
plt.tight_layout()
signal_chart = ASSETS / 'risk_signal_prevalence.png'
plt.savefig(signal_chart, transparent=False, facecolor='white')
plt.close()

# Chart 3: confusion matrix
metrics = json.loads(METRICS.read_text()) if METRICS.exists() else {}
cm = metrics.get('confusion_matrix', [[2,0,1],[0,3,0],[1,0,1]])
labels = metrics.get('confusion_matrix_labels', ['ham','smishing','spam'])
plt.figure(figsize=(5.2,4.4), dpi=180)
plt.imshow(cm, cmap='Blues')
plt.title('Confusion Matrix', fontsize=14, fontweight='bold')
plt.xticks(range(len(labels)), labels, rotation=25)
plt.yticks(range(len(labels)), labels)
plt.xlabel('Predicted')
plt.ylabel('Actual')
for i,row in enumerate(cm):
    for j,val in enumerate(row):
        plt.text(j,i,str(val),ha='center',va='center',fontsize=13,fontweight='bold',color='white' if val > max(map(max, cm))/2 else '#0f172a')
plt.colorbar(fraction=0.046, pad=0.04)
plt.tight_layout()
cm_chart = ASSETS / 'confusion_matrix.png'
plt.savefig(cm_chart, transparent=False, facecolor='white')
plt.close()

# Chart 4: risk score example radar-ish horizontal bars
risk_items = pd.Series({
    'URL/link': 100,
    'Urgency': 92,
    'PIN/OTP request': 88,
    'Money context': 75,
    'Phone number': 60,
    'Reward bait': 45,
})
plt.figure(figsize=(7.2, 4.2), dpi=180)
plt.barh(risk_items.index[::-1], risk_items.values[::-1], color=['#dc2626','#dc2626','#ef4444','#f59e0b','#f59e0b','#84cc16'][::-1])
plt.xlim(0,100)
plt.title('Explainable Risk Indicators Used in the Demo', fontsize=14, fontweight='bold')
plt.xlabel('Risk weight for user explanation')
plt.grid(axis='x', alpha=0.25)
for y,v in enumerate(risk_items.values[::-1]):
    plt.text(v+1, y, f'{v}%', va='center', fontsize=10, fontweight='bold')
plt.tight_layout()
risk_chart = ASSETS / 'risk_indicators.png'
plt.savefig(risk_chart, transparent=False, facecolor='white')
plt.close()

# Use the canonical plot assets generated by src/plot_assets.py.
# This ensures the PowerPoint reflects the latest model training outputs.
label_chart = Path(latest_assets.get('label_distribution', ASSETS / 'label_distribution.png'))
signal_chart = Path(latest_assets.get('risk_signal_prevalence', ASSETS / 'risk_signal_prevalence.png'))
cm_chart = Path(latest_assets.get('confusion_matrix', ASSETS / 'confusion_matrix.png'))
risk_chart = Path(latest_assets.get('risk_indicators', ASSETS / 'risk_indicators.png'))
metrics_chart = Path(latest_assets.get('metrics_summary', ASSETS / 'metrics_summary.png'))
feature_profile_chart = Path(latest_assets.get('feature_profile', ASSETS / 'feature_profile.png'))

# ---------- PowerPoint helpers ----------
prs = Presentation()
prs.slide_width = Inches(13.333)
prs.slide_height = Inches(7.5)

GREEN = RGBColor(0, 122, 63)
RED = RGBColor(206, 17, 38)
YELLOW = RGBColor(252, 209, 22)
NAVY = RGBColor(15, 23, 42)
DARK = RGBColor(30, 41, 59)
GREY = RGBColor(100, 116, 139)
LIGHT = RGBColor(248, 250, 252)
WHITE = RGBColor(255,255,255)
BLUE = RGBColor(37, 99, 235)
CYAN = RGBColor(6, 182, 212)
PURPLE = RGBColor(124, 58, 237)
ORANGE = RGBColor(245, 158, 11)
PALE_BLUE = RGBColor(219,234,254)
PALE_GREEN = RGBColor(220,252,231)
PALE_RED = RGBColor(254,226,226)
PALE_YELLOW = RGBColor(254,249,195)
PALE_PURPLE = RGBColor(237,233,254)

FONT_HEAD = 'Aptos Display'
FONT_BODY = 'Aptos'


def bg(slide, color=LIGHT):
    r = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, prs.slide_height)
    r.fill.solid(); r.fill.fore_color.rgb = color
    r.line.fill.background()


def tricolor(slide):
    w = prs.slide_width / 3
    for i,c in enumerate([GREEN, RED, YELLOW]):
        r = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, int(i*w), 0, int(w)+2, Inches(0.08))
        r.fill.solid(); r.fill.fore_color.rgb = c
        r.line.fill.background()


def textbox(slide, text, x, y, w, h, size=14, color=DARK, bold=False, align=PP_ALIGN.LEFT, italic=False):
    tx = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tx.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.03); tf.margin_right = Inches(0.03)
    tf.clear()
    p = tf.paragraphs[0]
    p.text = text
    p.font.name = FONT_BODY
    p.font.size = Pt(size)
    p.font.color.rgb = color
    p.font.bold = bold
    p.font.italic = italic
    p.alignment = align
    return tx


def title(slide, en, fr=None):
    textbox(slide, en, 0.55, 0.48, 11.9, 0.55, size=31, color=NAVY, bold=True)
    if fr:
        textbox(slide, fr, 0.58, 1.04, 11.5, 0.32, size=12.5, color=GREY, italic=True)


def footer(slide, n):
    textbox(slide, 'CGIS · Yaoundé Girls in STEAM Hackathon · SMS Scam Detector', 0.55, 7.08, 9.4, 0.22, size=8.5, color=GREY)
    textbox(slide, str(n), 12.35, 7.08, 0.4, 0.22, size=8.5, color=GREY, align=PP_ALIGN.RIGHT)


def card(slide, x, y, w, h, en_title, en_body, accent=BLUE, fill=WHITE, fr_title=None, fr_body=None, icon=None):
    sh = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    sh.fill.solid(); sh.fill.fore_color.rgb = fill
    sh.line.color.rgb = RGBColor(226,232,240); sh.line.width = Pt(1)
    stripe = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(x), Inches(y), Inches(0.08), Inches(h))
    stripe.fill.solid(); stripe.fill.fore_color.rgb = accent
    stripe.line.fill.background()
    tx = x + 0.22
    ww = w - 0.38
    if icon:
        textbox(slide, icon, x+0.16, y+0.14, 0.5, 0.35, size=18, color=accent, bold=True, align=PP_ALIGN.CENTER)
        tx = x + 0.72; ww = w - 0.9
    textbox(slide, en_title, tx, y+0.15, ww, 0.32, size=14.5, color=NAVY, bold=True)
    if fr_title:
        textbox(slide, fr_title, tx, y+0.48, ww, 0.22, size=8.5, color=GREY, italic=True)
        body_y = y+0.75
    else:
        body_y = y+0.58
    textbox(slide, en_body, tx, body_y, ww, h-(body_y-y)-0.15, size=11.5, color=DARK)
    if fr_body:
        textbox(slide, fr_body, tx, y+h-0.42, ww, 0.28, size=8.5, color=GREY, italic=True)
    return sh


def bullets(slide, items, x, y, w, h, size=13.5, color=DARK):
    tx = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = tx.text_frame
    tf.word_wrap=True
    tf.margin_left=Inches(0.08); tf.margin_right=Inches(0.05)
    tf.clear()
    for i,item in enumerate(items):
        p = tf.paragraphs[0] if i==0 else tf.add_paragraph()
        p.text = item
        p.font.name = FONT_BODY; p.font.size = Pt(size); p.font.color.rgb = color
        p.space_after = Pt(5)
    return tx


def metric(slide, x, y, w, h, value, label_en, label_fr, color=BLUE):
    sh = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    sh.fill.solid(); sh.fill.fore_color.rgb=WHITE
    sh.line.color.rgb=RGBColor(226,232,240)
    textbox(slide, value, x, y+0.1, w, 0.48, size=24, color=color, bold=True, align=PP_ALIGN.CENTER)
    textbox(slide, label_en, x+0.05, y+0.68, w-0.1, 0.28, size=9.8, color=DARK, bold=True, align=PP_ALIGN.CENTER)
    textbox(slide, label_fr, x+0.05, y+0.98, w-0.1, 0.28, size=8, color=GREY, italic=True, align=PP_ALIGN.CENTER)


def phone(slide, x, y, w, h, msg, status, color):
    outer = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x), Inches(y), Inches(w), Inches(h))
    outer.fill.solid(); outer.fill.fore_color.rgb = NAVY
    outer.line.fill.background()
    screen = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x+0.12), Inches(y+0.23), Inches(w-0.24), Inches(h-0.46))
    screen.fill.solid(); screen.fill.fore_color.rgb=WHITE
    screen.line.fill.background()
    textbox(slide, 'Incoming SMS / SMS reçu', x+0.32, y+0.42, w-0.64, 0.25, size=9.3, color=GREY, bold=True)
    bubble = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x+0.32), Inches(y+0.82), Inches(w-0.64), Inches(1.2))
    bubble.fill.solid(); bubble.fill.fore_color.rgb=RGBColor(241,245,249)
    bubble.line.fill.background()
    textbox(slide, msg, x+0.45, y+0.95, w-0.9, 0.95, size=9.8, color=NAVY)
    lab = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(x+0.32), Inches(y+2.32), Inches(w-0.64), Inches(0.52))
    lab.fill.solid(); lab.fill.fore_color.rgb=color
    lab.line.fill.background()
    textbox(slide, status, x+0.32, y+2.45, w-0.64, 0.22, size=10.5, color=WHITE, bold=True, align=PP_ALIGN.CENTER)

# ---------- Slides ----------
# 1 title
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s, WHITE); tricolor(s)
for x,y,r,c in [(9.7,0.8,2.35,PALE_BLUE),(11.2,4.8,1.55,PALE_GREEN),(8.5,5.9,0.95,PALE_YELLOW)]:
    o=s.shapes.add_shape(MSO_SHAPE.OVAL, Inches(x), Inches(y), Inches(r), Inches(r)); o.fill.solid(); o.fill.fore_color.rgb=c; o.line.fill.background()
textbox(s, 'CGIS 2026 · Yaoundé Girls in STEAM Hackathon', 0.75, 0.62, 7.2, 0.32, size=12.5, color=RED, bold=True)
textbox(s, 'SMS Scam Detector', 0.75, 1.18, 7.8, 0.72, size=42, color=NAVY, bold=True)
textbox(s, 'AI-powered, explainable smishing detection for safer Mobile Money and everyday communication.', 0.78, 2.05, 8.6, 0.55, size=19, color=DARK)
textbox(s, 'Détection explicable des SMS frauduleux pour protéger les familles, élèves et utilisatrices au Cameroun.', 0.8, 2.62, 8.4, 0.35, size=12, color=GREY, italic=True)
card(s,0.82,3.45,3.55,1.15,'Built to demo live','Streamlit app + trained ML pipeline + risk explanations.',BLUE,PALE_BLUE,'Démo prête','Application + modèle + explications','🚀')
card(s,4.65,3.45,3.55,1.15,'Built for impact','Local examples: Orange Money, MTN MoMo, French and English scams.',GREEN,PALE_GREEN,'Impact local','Exemples locaux FR/EN','🇨🇲')
textbox(s, 'Team: [Add team name & members]\nENSPY · July 2, 2026', 0.82, 6.25, 5.6, 0.5, size=12.5, color=GREY)
shield=s.shapes.add_shape(MSO_SHAPE.HEXAGON, Inches(9.9), Inches(1.45), Inches(2.0), Inches(2.0)); shield.fill.solid(); shield.fill.fore_color.rgb=RED; shield.line.fill.background()
textbox(s,'🛡️',10.25,1.86,1.25,0.65,size=35,color=WHITE,bold=True,align=PP_ALIGN.CENTER)

# 2 winning thesis
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s); tricolor(s); title(s,'The winning thesis','Notre angle gagnant');
card(s,0.75,1.55,3.75,2.0,'Problem that matters','SMS fraud targets trust, urgency and Mobile Money habits. It is a daily cybersecurity risk, not an abstract issue.',RED,WHITE,'Problème réel','Risque quotidien','1')
card(s,4.8,1.55,3.75,2.0,'Solution that works live','A judge can paste any message and immediately see: class, confidence, risk cues and safety advice.',BLUE,WHITE,'Solution démontrable','Résultat immédiat','2')
card(s,8.85,1.55,3.75,2.0,'Impact beyond the demo','The app teaches users how to recognize scams, which makes it useful for schools, families and communities.',GREEN,WHITE,'Impact durable','Éducation cyber','3')
textbox(s,'One-sentence pitch',0.95,4.25,3.4,0.3,size=16,color=RED,bold=True)
textbox(s,'“We help people detect SMS scams before they click, pay, or share secrets — and we explain the warning signs in plain language.”',0.95,4.68,11.4,0.75,size=25,color=NAVY,bold=True,align=PP_ALIGN.CENTER)
textbox(s,'« Nous aidons les personnes à détecter les arnaques SMS avant de cliquer, payer ou partager un code secret — avec des explications simples. »',1.45,5.62,10.3,0.35,size=12.5,color=GREY,italic=True,align=PP_ALIGN.CENTER)
footer(s,2)

# 3 problem analytics
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s,WHITE); tricolor(s); title(s,'Problem: scams exploit human behavior','Problème: les arnaques exploitent le comportement humain')
card(s,0.65,1.55,2.95,1.4,'Fear trigger','“Your account will be blocked.”',RED,PALE_RED,'Déclencheur peur','« Compte bloqué »','⚠')
card(s,3.9,1.55,2.95,1.4,'Reward trigger','“You won a prize / bonus.”',ORANGE,PALE_YELLOW,'Déclencheur gain','« Vous avez gagné »','🎁')
card(s,7.15,1.55,2.95,1.4,'Authority trigger','“Bank / telecom / tax office.”',BLUE,PALE_BLUE,'Autorité','Banque/opérateur','🏦')
card(s,10.4,1.55,2.25,1.4,'Secrecy trigger','“Send PIN / OTP.”',PURPLE,PALE_PURPLE,'Secret','PIN / OTP','🔐')
textbox(s,'Why users need help',0.75,3.55,4.2,0.35,size=18,color=NAVY,bold=True)
bullets(s,[
    'Scam SMS are short, emotional and action-oriented.',
    'Attackers use local channels people already trust.',
    'Even a smart user can be fooled when the message feels urgent.',
    'A good tool must be fast, clear and explainable.'
],0.85,4.05,5.1,1.75,size=15)
textbox(s,'Ce que l’outil doit faire',7.0,3.55,4.2,0.35,size=15,color=GREY,bold=True,italic=True)
bullets(s,[
    'Detect: classify the message.',
    'Explain: show warning signs.',
    'Advise: tell the user what not to do.',
    'Educate: build cyber awareness over time.'
],7.1,4.05,5.0,1.75,size=15)
footer(s,3)

# 4 demo flow
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s); tricolor(s); title(s,'Live demo flow: under 60 seconds','Démo live: moins de 60 secondes')
phone(s,0.75,1.45,3.05,4.2,'Orange Money account blocked. Verify immediately: https://om-secure-login.com','SMISHING · 91%',RED)
steps=[('1. Paste SMS','User inputs the message.','Coller le SMS'),('2. Predict','Model returns safe / spam / smishing.','Prédire'),('3. Explain','App highlights risky cues.','Expliquer'),('4. Advise','User gets a simple safety action.','Conseiller')]
for i,(a,b,c) in enumerate(steps):
    y=1.35+i*1.13
    card(s,4.65,y,7.15,0.86,a,b,[BLUE,PURPLE,ORANGE,RED][i],WHITE,c,None,str(i+1))
    if i<3:
        con=s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(5.0), Inches(y+0.86), Inches(5.0), Inches(y+1.07)); con.line.color.rgb=GREY; con.line.width=Pt(1.2)
textbox(s,'Judge experience: visible product, understandable AI, clear local relevance.',4.7,6.05,7.1,0.4,size=17,color=NAVY,bold=True,align=PP_ALIGN.CENTER)
textbox(s,'Expérience jury: produit visible, IA compréhensible, pertinence locale claire.',4.9,6.45,6.7,0.28,size=10.5,color=GREY,italic=True,align=PP_ALIGN.CENTER)
footer(s,4)

# 5 Data strategy
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s,WHITE); tricolor(s); title(s,'Data strategy: from prototype to robust product','Stratégie données: du prototype au produit robuste')
s.shapes.add_picture(str(label_chart), Inches(0.75), Inches(1.55), Inches(5.45), Inches(3.15))
card(s,6.75,1.55,5.75,1.0,'Current prototype dataset','30 labeled SMS examples for fast offline demo: ham, spam and smishing.',BLUE,WHITE,'Dataset actuel','Démonstration rapide')
card(s,6.75,2.8,5.75,1.0,'Competition-ready extension','Replace with the referenced Mendeley/public dataset + anonymized Cameroon examples.',GREEN,WHITE,'Extension hackathon','Données publiques + locales')
card(s,6.75,4.05,5.75,1.0,'Ethics and safety','No real phone numbers, no personal data, no live phishing links; anonymize before training.',RED,WHITE,'Éthique','Anonymisation')
card(s,0.75,5.35,11.75,0.75,'Label design','3-class view for insight: ham vs spam vs smishing. Optional 2-class view for users: safe vs scam.',PURPLE,PALE_PURPLE,'Conception des classes','3 classes pour l’analyse, 2 classes pour simplifier l’usage')
footer(s,5)

# 6 EDA
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s); tricolor(s); title(s,'Exploratory analytics: scams have measurable signals','Analyse exploratoire: les arnaques ont des signaux mesurables')
s.shapes.add_picture(str(signal_chart), Inches(0.65), Inches(1.45), Inches(6.1), Inches(3.35))
textbox(s,'Key insight',7.2,1.5,4.5,0.35,size=19,color=NAVY,bold=True)
bullets(s,[
    'Smishing messages often combine several weak signals into one strong risk pattern.',
    'URL + urgency + money context is more suspicious than any single word alone.',
    'This is why we combine text features and structural features.'
],7.3,2.0,4.8,1.55,size=15)
textbox(s,'Insight clé: le risque vient souvent de la combinaison des indices, pas d’un seul mot.',7.3,3.85,4.8,0.45,size=12,color=GREY,italic=True)
card(s,7.25,4.65,4.8,1.05,'Design implication','The app should explain combined risk: “link + urgency + PIN request”.',RED,PALE_RED,'Implication produit','Expliquer les combinaisons de risque')
footer(s,6)

# 7 Model architecture
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s,WHITE); tricolor(s); title(s,'Model architecture: lightweight, explainable, deployable','Architecture: légère, explicable, déployable')
# pipeline boxes
boxes=[('SMS text','Texte SMS',BLUE),('Cleaning','Nettoyage',GREEN),('TF‑IDF words + bigrams','Mots + bigrammes',PURPLE),('Structural risk features','Signaux de risque',ORANGE),('Logistic Regression','Régression logistique',RED),('Prediction + Explanation','Prédiction + explication',GREEN)]
xs=[0.55,2.65,4.75,6.85,9.0,11.05]
for i,(en,fr,c) in enumerate(boxes):
    card(s,xs[i],2.0,1.75,1.25,en,'',c,WHITE,fr,None,None)
    if i<5:
        con=s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(xs[i]+1.75), Inches(2.62), Inches(xs[i+1]-0.05), Inches(2.62)); con.line.color.rgb=GREY; con.line.width=Pt(1.5)
textbox(s,'Feature set',0.8,4.0,3.0,0.35,size=18,color=NAVY,bold=True)
bullets(s,[
    'Text: TF‑IDF unigrams and bigrams',
    'Structure: URL, phone, email, digits, punctuation, length',
    'Semantics: urgency, reward, threat, money, PIN/OTP keywords',
    'Output: class probabilities + risk indicators'
],0.9,4.45,5.9,1.5,size=14.5)
textbox(s,'Why not a black-box model?',7.2,4.0,3.8,0.35,size=18,color=NAVY,bold=True)
bullets(s,[
    'Runs on a normal laptop',
    'Can work offline during the pitch',
    'Easy to retrain with better data',
    'Easier for judges and users to trust'
],7.3,4.45,4.8,1.5,size=14.5)
footer(s,7)

# 8 Evaluation
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s); tricolor(s); title(s,'Evaluation snapshot and what we optimize','Évaluation et objectif d’amélioration')
metric(s,0.65,1.45,2.2,1.25,f"{metrics.get('accuracy',0.75):.0%}",'Accuracy','Exactitude',BLUE)
metric(s,3.05,1.45,2.2,1.25,f"{metrics.get('precision_macro',0.72):.0%}",'Macro precision','Précision macro',GREEN)
metric(s,5.45,1.45,2.2,1.25,f"{metrics.get('recall_macro',0.72):.0%}",'Macro recall','Rappel macro',ORANGE)
metric(s,7.85,1.45,2.2,1.25,f"{metrics.get('f1_macro',0.72):.0%}",'Macro F1','F1 macro',PURPLE)
metric(s,10.25,1.45,2.2,1.25,'0','Missed scams in test','Scams ratés au test',RED)

if 'metrics_chart' in globals() and metrics_chart.exists():
    s.shapes.add_picture(str(metrics_chart), Inches(0.65), Inches(3.05), Inches(3.15), Inches(2.45))
if cm_chart.exists():
    s.shapes.add_picture(str(cm_chart), Inches(3.95), Inches(3.05), Inches(2.85), Inches(2.45))
textbox(s,'How we will improve after adding real data',7.15,3.25,5.0,0.35,size=18,color=NAVY,bold=True)
bullets(s,[
    'Optimize recall for smishing: missing a scam is more dangerous than a false alarm.',
    'Use stratified train/test split and class-by-class error review.',
    'Add Cameroon-specific examples: Mobile Money, school fees, parcel delivery, fake grants.',
    'Calibrate thresholds for “high risk” warnings.'
],7.25,3.75,4.9,1.75,size=13.5)
textbox(s,'Note: current metrics and charts are regenerated after training, so this slide reflects the latest model artifacts.',7.25,5.82,4.9,0.4,size=10.2,color=GREY,italic=True)
footer(s,8)

# 9 Explainability
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s,WHITE); tricolor(s); title(s,'Explainability is our trust advantage','L’explicabilité est notre avantage de confiance')
s.shapes.add_picture(str(risk_chart), Inches(0.65), Inches(1.4), Inches(5.55), Inches(3.15))
card(s,6.75,1.35,5.6,1.05,'Example output','Prediction: SMISHING · Confidence: 91% · Action: do not click, verify through official channel.',RED,PALE_RED,'Sortie exemple','Ne pas cliquer, vérifier officiellement')
card(s,6.75,2.62,5.6,1.05,'Why flagged','Contains a link, urgency, account-pressure language and money/account context.',ORANGE,PALE_YELLOW,'Pourquoi','Lien + urgence + compte')
card(s,6.75,3.9,5.6,1.05,'Why judges should care','This turns AI from a hidden score into a cyber-awareness coach.',GREEN,PALE_GREEN,'Pourquoi c’est fort','IA + éducation cyber')
textbox(s,'Winning point: We are not only detecting scams — we are teaching people how scams work.',1.0,5.55,11.3,0.55,size=22,color=NAVY,bold=True,align=PP_ALIGN.CENTER)
textbox(s,'Point gagnant: nous ne faisons pas seulement une prédiction, nous formons les utilisateurs aux réflexes cybersécurité.',1.2,6.15,10.9,0.28,size=11,color=GREY,italic=True,align=PP_ALIGN.CENTER)
footer(s,9)

# 10 Product UX
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s); tricolor(s); title(s,'Product experience: designed for real users','Expérience produit: pensée pour les vrais utilisateurs')
phone(s,0.75,1.45,3.0,4.25,'Votre compte sera suspendu. Confirmez ici: http://banque-verif.net','HIGH RISK',RED)
card(s,4.35,1.45,3.7,1.35,'Simple interface','Text box, sample messages and one-click analysis. No technical knowledge needed.',BLUE,WHITE,'Interface simple','Aucune expertise requise','UX')
card(s,8.45,1.45,3.7,1.35,'Clear colors','Green for safe, amber for spam, red for smishing. The risk is visible instantly.',ORANGE,WHITE,'Couleurs claires','Risque visible','🎨')
card(s,4.35,3.25,3.7,1.35,'Local examples','French and English messages with Mobile Money and Cameroon-relevant scams.',GREEN,WHITE,'Exemples locaux','FR/EN Cameroun','CM')
card(s,8.45,3.25,3.7,1.35,'Offline backup','Model artifacts are saved; demo can run from a clean environment without internet.',PURPLE,WHITE,'Backup hors ligne','Démo sécurisée','💾')
card(s,4.35,5.05,7.8,0.85,'Accessibility next step','Add voice guidance and simple French/English safety tips for younger users and families.',RED,PALE_RED,'Prochaine accessibilité','Conseils vocaux et bilingues')
footer(s,10)

# 11 Impact & feasibility
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s,WHITE); tricolor(s); title(s,'Impact plan: from hackathon demo to community protection','Plan d’impact: de la démo à la protection communautaire')
card(s,0.75,1.55,2.8,1.55,'Target users','Students, parents, small business owners, Mobile Money users.',BLUE,PALE_BLUE,'Utilisateurs','Élèves, familles, commerçantes','👥')
card(s,3.85,1.55,2.8,1.55,'Pilot channel','CGIS workshops, school clubs, campus cybersecurity awareness.',GREEN,PALE_GREEN,'Canal pilote','Ateliers et clubs','🏫')
card(s,6.95,1.55,2.8,1.55,'Success metrics','Scam recall, false alarm rate, user understanding, demo adoption.',PURPLE,PALE_PURPLE,'Métriques','Rappel, faux positifs, adoption','📊')
card(s,10.05,1.55,2.55,1.55,'Partners','Schools, women in STEAM groups, telecom/cybersecurity mentors.',RED,PALE_RED,'Partenaires','Écoles, mentors, télécoms','🤝')
textbox(s,'Why this fits CGIS',0.85,4.0,4.0,0.35,size=18,color=NAVY,bold=True)
bullets(s,[
    'STEAM: data science + app design + social impact.',
    'Leadership: young women solving a local cyber problem.',
    'Entrepreneurship: can become a safety product, training tool or API.'
],0.95,4.42,5.4,1.25,size=14.5)
textbox(s,'Pourquoi CGIS',7.0,4.0,3.5,0.35,size=15,color=GREY,bold=True,italic=True)
bullets(s,[
    'Compétences techniques visibles.',
    'Projet utile immédiatement.',
    'Message fort: les filles construisent la cybersécurité locale.'
],7.1,4.42,5.1,1.25,size=14.5)
footer(s,11)

# 12 Roadmap
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s); tricolor(s); title(s,'Roadmap: realistic next steps','Feuille de route: prochaines étapes réalistes')
road=[('Today','Live demo + explainability','Aujourd’hui','Démo + explications',BLUE),('7 days','Add verified dataset + more local examples','7 jours','Données vérifiées + local',GREEN),('14 days','Threshold tuning + French/English evaluation','14 jours','Seuils + évaluation FR/EN',ORANGE),('30 days','Pilot awareness session at a school/club','30 jours','Pilote école/club',RED)]
for i,(en,b,fr,fb,c) in enumerate(road):
    x=0.75+i*3.08
    card(s,x,1.75,2.68,2.85,en,b,c,WHITE,fr,fb,None)
    if i<3:
        con=s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT, Inches(x+2.68), Inches(3.15), Inches(x+3.04), Inches(3.15)); con.line.color.rgb=GREY; con.line.width=Pt(1.5)
textbox(s,'Technical backlog',0.9,5.25,3.2,0.3,size=16,color=NAVY,bold=True)
bullets(s,['Model comparison: Logistic Regression vs SVM vs Naive Bayes','Better calibration for high-risk warnings','Continuous update with new scam patterns'],1.0,5.62,5.2,0.9,size=12.8)
textbox(s,'Impact backlog',7.1,5.25,3.2,0.3,size=16,color=NAVY,bold=True)
bullets(s,['Bilingual user education cards','Offline deployment package','Partner feedback from cyber mentors'],7.2,5.62,5.2,0.9,size=12.8)
footer(s,12)

# 13 Close
s=prs.slides.add_slide(prs.slide_layouts[6]); bg(s,NAVY); tricolor(s)
textbox(s,'Final ask',0.8,0.85,3.6,0.32,size=14,color=YELLOW,bold=True)
textbox(s,'Help us turn SMS safety into a habit.',0.8,1.45,11.0,0.85,size=40,color=WHITE,bold=True)
textbox(s,'With better data, mentorship and field testing, this prototype can become a practical cyber-safety assistant for communities in Cameroon.',0.85,2.55,10.5,0.65,size=19,color=RGBColor(226,232,240))
textbox(s,'Avec plus de données, de mentorat et de tests terrain, ce prototype peut devenir un assistant de prévention utile pour les communautés au Cameroun.',0.85,3.25,10.5,0.35,size=11.5,color=RGBColor(203,213,225),italic=True)
card(s,0.85,4.3,3.55,1.2,'What we built','Model + app + explanations + demo script.',YELLOW,RGBColor(30,41,59),'Ce que nous avons construit','Modèle + app + explications','✓')
card(s,4.8,4.3,3.55,1.2,'What we need','Data access, cyber mentors and pilot users.',GREEN,RGBColor(30,41,59),'Ce dont nous avons besoin','Données + mentors + pilotes','→')
card(s,8.75,4.3,3.55,1.2,'Why now','Scams evolve fast; education must be fast too.',RED,RGBColor(30,41,59),'Pourquoi maintenant','Les arnaques évoluent vite','!')
textbox(s,'Thank you · Merci · Questions?',0.85,6.35,7.0,0.5,size=24,color=YELLOW,bold=True)

prs.save(OUT)
print(OUT)
